services:
  nginx1:
    build:
      context: ./nginx
    container_name: nginx1
    ports:
      - "8081:80"
    volumes:
      - ./nginx/content:/usr/share/nginx/html/content
      - ./logs/nginx1:/var/log/nginx
    networks:
      - cdn-network

  nginx2:
    build:
      context: ./nginx
    container_name: nginx2
    ports:
      - "8082:80"
    volumes:
      - ./nginx/content:/usr/share/nginx/html/content
      - ./logs/nginx2:/var/log/nginx 
    networks:
      - cdn-network

  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-prometheus-exporter
    command: ["--nginx.scrape-uri=http://nginx1/status",
    "--nginx.scrape-uri=http://nginx2/status",
    "--log.level=debug"]
    ports:
      - "9113:9113"
    networks:
      - cdn-network
    depends_on:
      - nginx1
      - nginx2

  nginx-proxy:
    build:
      context: ./nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    networks:
      - cdn-network
    depends_on:
      - nginx1
      - nginx2

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - cdn-network
    depends_on:
      - nginx-prometheus-exporter

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_LOG_LEVEL=warn
    networks:
      - cdn-network
    depends_on:
      - prometheus

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5000:80"
    networks:
      - cdn-network

networks:
  cdn-network:
    driver: bridge
