services:
  nginx1:
    build:
      context: ./nginx
    container_name: nginx1
    ports:
      - "8081:80"
    volumes:
      - ./nginx/content:/usr/share/nginx/html
    networks:
      - cdn-network

  nginx2:
    build:
      context: ./nginx
    container_name: nginx2
    ports:
      - "8082:80"
    volumes:
      - ./nginx/content:/usr/share/nginx/html
    networks:
      - cdn-network

  nginx-proxy:
    build:
      context: ./nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    networks:
      - cdn-network
    depends_on:
      - nginx1
      - nginx2

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - cdn-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - cdn-network
    depends_on:
      - prometheus

  elasticsearch:
    image: elasticsearch:8.16.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - cdn-network

  logstash:
    image: logstash:8.16.1
    container_name: logstash
    ports:
      - "5044:5044"
    networks:
      - cdn-network
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:8.16.1
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - cdn-network
    depends_on:
      - elasticsearch

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3001:3000"
    networks:
      - cdn-network

networks:
  cdn-network:
    driver: bridge
